### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by hjbrock** [TheLoons/SportIM-web#10]
Create 2-3 SportIM logos with a field in the background.

**Comment by boccobrock** [comment]
![newlogo](https://cloud.githubusercontent.com/assets/1638004/5867888/e3a1c3e8-a25e-11e4-809b-83b1129fb949.png)

We have decided to go with a simpler css based logo for now. Closing the ticket as we will likely use this logo and make minor changes to it as we move forward.
